name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:

    runs-on: ubuntu-latest
    container: doubleailes/rust-docker-nextest:0.1.1

    steps:
    - uses: actions/checkout@v2
    - name: Bench
      run: cargo bench