on:  
  push:
    tags:
      - '*'
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          BUILD_DIR: docs
          TOKEN: ${{ secrets.GITHUB_TOKEN }}