name: Publish in create

on:  
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: doubleailes/rust-docker-nextest:0.1.0

    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
        - uses: katyo/publish-crates@v1
          with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}