name: Publish in create

on:  
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest
    container: ghcr.io/doubleailes/rust-docker-nextest:latest

    steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
          with:
              toolchain: stable
              override: true
        - name: 🏷️ Tag Version
          run: cargo bump ${{ github.ref }}
        - uses: katyo/publish-crates@v2
          with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}