[package]
name = "framels-core"
version = "0.1.0"
edition ={ workspace = true}
authors = { workspace = true}
description = "a lib to pack file sequences manily for animation and vfx"
readme = { workspace = true}
license-file = { workspace = true}
repository = { workspace = true}
